kind: pipeline
type: docker
name: default

steps:
- name: install_dependencies
  image: node
  commands:
  - cd server
  - npm install
  - cd ../web_app
  - npm install

- name: run_dev_servers
  image: node
  commands:
  - cd server
  - npm run dev &
  - echo $! > server_pid
  - cd ../web_app
  - npm run dev &
  - echo $! > web_app_pid

- name: stop_dev_servers
  image: node
  commands:
  - kill $(cat web_app_pid)
  - cd ../server
  - kill $(cat server_pid)
