kind: pipeline
type: docker
name: default

volumes:
- name: shared
  temp: {}

steps:
- name: install_dependencies
  image: node
  volumes:
  - name: shared
    path: /drone/src/shared
  commands:
  - cd server
  - npm install
  - cd ../web_app
  - npm install

- name: run_server
  image: node
  volumes:
  - name: shared
    path: /drone/src/shared
  commands:
  - cd ../server
  - npm run dev &
  - echo $! > /drone/src/shared/server_pid
  - echo "Server PID: $(cat /drone/src/shared/server_pid)"
  - sleep 5

- name: run_web_app
  image: node
  volumes:
  - name: shared
    path: /drone/src/shared
  commands:
  - cd ../web_app
  - npm run dev &
  - echo $! > /drone/src/shared/web_app_pid
  - echo "Web App PID: $(cat /drone/src/shared/web_app_pid)"
  - sleep 5

- name: stop_server
  image: node
  volumes:
  - name: shared
    path: /drone/src/shared
  commands:
  - echo "Stopping Server"
  - cat /drone/src/shared/server_pid
  - kill $(cat /drone/src/shared/server_pid)

- name: stop_web_app
  image: node
  volumes:
  - name: shared
    path: /drone/src/shared
  commands:
  - echo "Stopping Web App"
  - cat /drone/src/shared/web_app_pid
  - kill $(cat /drone/src/shared/web_app_pid)
