kind: pipeline
type: docker
name: default

steps:
- name: install_dependencies
  image: node
  commands:
  - cd server
  - npm install
  - cd ../web_app
  - npm install

- name: run_dev_servers
  image: node
  commands:
  - cd server
  - npm run dev &
  - echo $! > /tmp/server_pid
  - echo "Server PID: $(cat /tmp/server_pid)"
  - sleep 5
  - cd ../web_app
  - npm run dev &
  - echo $! > /tmp/web_app_pid
  - echo "Web App PID: $(cat /tmp/web_app_pid)"
  - sleep 5

- name: stop_dev_servers
  image: node
  commands:
  - |
    if [ -f /tmp/web_app_pid ]; then
      echo "Stopping Web App..."
      cat /tmp/web_app_pid
      kill $(cat /tmp/web_app_pid)
    else
      echo "Web App PID file not found!"
    fi
  - |
    if [ -f /tmp/server_pid ]; then
      echo "Stopping Server..."
      cat /tmp/server_pid
      kill $(cat /tmp/server_pid)
    else
      echo "Server PID file not found!"
    fi
