kind: pipeline
type: docker
name: default

steps:
- name: install_pm2
  image: node
  commands:
  - npm install -g pm2

- name: install_dependencies
  image: node
  commands:
  - cd server
  - npm install
  - cd ../web_app
  - npm install

- name: run_dev_servers
  image: node
  commands:
  - cd server
  - pm2 start npm --name "server" -- run dev
  - cd ../web_app
  - pm2 start npm --name "web_app" -- run dev

- name: check_server_running
  image: node
  commands:
  - apt-get update && apt-get install -y curl
  - sleep 10  # wait for the server to start
  - curl -f http://localhost:6060 || exit 1  # check the server endpoint, adjust the port as needed
  - curl -f http://localhost:5173 || exit 1  # check the web_app endpoint, adjust the port as needed

- name: stop_dev_servers
  image: node
  commands:
  - pm2 stop all
  - pm2 delete all
