kind: pipeline
type: docker
name: default

steps:
- name: install_dependencies
  image: node
  commands:
  - cd server
  - npm install
  - cd ../web_app
  - npm install

- name: run_dev_servers
  image: node
  commands:
  - cd server
  - npm run dev &
  - echo $! > /tmp/server_pid
  - sleep 5  # Add a delay to ensure the server has time to start and write its PID
  - cd ../web_app
  - npm run dev &
  - echo $! > /tmp/web_app_pid
  - sleep 5  # Add a delay to ensure the web app has time to start and write its PID

- name: stop_dev_servers
  image: node
  commands:
  - kill $(cat /tmp/web_app_pid)
  - kill $(cat /tmp/server_pid)
