kind: pipeline
type: docker
name: default

steps:
- name: install_dependencies
  image: node
  commands:
  # Navigate to the server directory and install dependencies
  - cd server
  - npm install
  # Navigate to the web_app directory and install dependencies
  - cd ../web_app
  - npm install

- name: run_dev_servers
  image: node
  commands:
  # Run the server in the background and capture its PID in an absolute path
  - cd server
  - npm run dev &
  - echo $! > /tmp/server_pid
  - cat /tmp/server_pid
  # Add a delay to ensure the server has time to start and write its PID
  - sleep 5
  # Run the web app in the background and capture its PID in an absolute path
  - cd ../web_app
  - npm run dev &
  - echo $! > /tmp/web_app_pid
  - cat /tmp/server_pid
  - cat /tmp/web_app_pid
  # Add a delay to ensure the web app has time to start and write its PID
  - sleep 5

- name: stop_dev_servers
  image: node
  commands:
  # Kill the web app process using its PID stored in /tmp/web_app_pid
  - kill $(cat /tmp/web_app_pid)
  # Kill the server process using its PID stored in /tmp/server_pid
  - kill $(cat /tmp/server_pid)

